//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEgitimAkademi.Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPartner
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Title2 { get; set; }
        public Nullable<int> ClientCount { get; set; }
        public Nullable<int> FeedBackQuality { get; set; }
        public Nullable<int> SponsorCount { get; set; }
    }
}
